server.port=8081
spring.application.name=parameter-micro-service
spring.datasource.url=jdbc:mysql://localhost:3306/parameter_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=ENC(KD1uVJPrxdskJaSjjz2whJ/kKAZP1Tfhi9iWYqmEZC5/FLW3owVHBgzqQLNae6sz)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true