spring.application.name=parameter-micro-service
server.port=8081

# Jasypt Anahtarı (Güvenli Kasadan)
jasypt.encryptor.password=${JASYPT_ENCRYPTOR_PASSWORD}

# Veritabanı Bağlantısı - Aiven MySQL (Sıfır Hardcode)
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/parameter_db?useSSL=true&requireSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate ve Liquibase Ayarları
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

# Spring Cloud Ayarları
spring.cloud.compatibility-verifier.enabled=false